CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_mame VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  last_login TIMESTAMPTZ DEFAULT CLOCK_TIMESTAMP(),
  company_id INTEGER NOT NULL REFRENCES company(id) ON DELETE CASCADE,
  phone_number INTEGER NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT FLASE,
  permission_level INTEGER DEFAULT 1,
)