CREATE TABLE venue (
  id SERIAL PRIMARY KEY NOT NULL,
  company_id INTEGER REFERENCES company(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  state INTEGER REFERENCES state(id) ON DELETE CASCADE
)