CREATE TABLE item (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NUll,
  sku VARCHAR(255) NOT NULL,
  vendor INTEGER REFERENCES vendor(id) ON DELETE CASCADE,
  size INTEGER REFERENCES size(id) ON DELETE CASCADE
)