CREATE TABLE item_count (
  id SERIAL PRIMARY KEY NOT NULL,
  count_info_id INTEGER REFERENCES count_info(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES item(id) ON DELETE CASCADE,
  storage_area_id INTEGER REFERENCES storage_area(id) ON DELETE CASCADE,
  count_value INTEGER NOT NULL,
  size INTEGER REFERENCES size(id) ON DELETE CASCADE
)